site_name: know-your-model

repo_url: https://gitlab.aimedic.tech/vision-group/know-your-model
repo_name: vision-group/know-your-model

theme:
  name: "material"

  icon:
    logo: logo
    repo: fontawesome/brands/gitlab

  favicon: favicon.ico

  features:
    - header.autohide
    - navigation.footer

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings

# Syntax Highlighting
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  homepage: https://docs.aimedic.tech/
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pejsamadi
      name: Pejman on Twitter

    - icon: fontawesome/brands/github
      link: https://github.com/pejmans21
      name: Pejman on GitHub

copyright: Copyright &copy; 2022 - 2023 Pejmans21

nav:
  - Index: index.md
  - KYM Toolkit: kym-toolkit.md
  - modules: modules.md
  - kym.cli: kym.cli.md
  - kym.hhd.viz: kym.hhd.viz.md
  - kym.hhd.utils: kym.hhd.utils.md
  - kym.hhd.main: kym.hhd.main.md
  - kym.hhd.components: kym.hhd.components.md
  - kym.hhd.dashboard: kym.hhd.dashboard.md
